apiVersion: v1
kind: Service
metadata:
  name: housekeeping-service
spec:
  type: NodePort
  selector:
    app: housekeeping-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084